### ISSUE TITLE
Docs fail to build

### ISSUE THREAD

**Issue by jeroen** [ropensci/patentsview#23]
Fails with:

```
Quitting from lines 20-44 (citation-networks.Rmd) 
Error : Query Internal Error
```

See https://dev.ropensci.org/blue/organizations/jenkins/patentsview/detail/patentsview/116/pipeline (or click on the red checkmark behind your last commit on github)

If your vignettes require special keys, you could consider to [precompute your vignettes](https://ropensci.org/technotes/2019/12/08/precompute-vignettes/).

**Comment by crew102** [comment]
Hi @jeroen , thanks for the heads up. I made a few small changes to the package that may or may not close this (the API's behavior is not predicable). I can build that vignette locally now, but I'm not sure if that's just coincidence. I'd prefer to compute the vignettes from scratch if possible, given that the API isn't hit all that hard in order to compute them and it would be nice to get a fresh version of the docs without having to precompute. If the issue persists, I'll go ahead and follow that blog post re: precomputing the vignettes.

**Comment by crew102** [comment]
Docs are now failing to build in a different vignette. Looks like there may be some problems with the APIs server right now. I've made a comment at https://github.com/PatentsView/PatentsView-API/issues/51#issuecomment-706447320 to try to get it resolved.

**Comment by jeroen** [comment]
I'm now seeing this error

```
Quitting from lines 93-113 (top-assignees.Rmd) 
Error in hc_add_series_df(highchart(), data = data, "line", x = app_yr,  : 
  could not find function "hc_add_series_df"
```

It looks like the `hc_add_series_df` no longer exists in highcharter, no idea why.

**Comment by crew102** [comment]
Yeah, I can't even import highcharter when I update to the latest version of that package (https://github.com/jbkunst/highcharter/issues/680). I guess I'll just precompute the vignettes to get around these issues.

I'll close this when I've worked through how to precompute.
